//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditingManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuditingManager.AuditEventFile", typeof(AuditEventFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ticket failed: {0}.
        /// </summary>
        internal static string AddParkingTicketFailure {
            get {
                return ResourceManager.GetString("AddParkingTicketFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket added successfully..
        /// </summary>
        internal static string AddParkingTicketSuccess {
            get {
                return ResourceManager.GetString("AddParkingTicketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed: {0}.
        /// </summary>
        internal static string AuthenticationFailure {
            get {
                return ResourceManager.GetString("AuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is successfully authenticated..
        /// </summary>
        internal static string AuthenticationSuccess {
            get {
                return ResourceManager.GetString("AuthenticationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed to access {1}. Reason: {2}..
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully accessed to {1}..
        /// </summary>
        internal static string AuthorizationSuccess {
            get {
                return ResourceManager.GetString("AuthorizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check payment failed: {0}.
        /// </summary>
        internal static string CheckPaymentFailure {
            get {
                return ResourceManager.GetString("CheckPaymentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check payment success..
        /// </summary>
        internal static string CheckPaymentSuccess {
            get {
                return ResourceManager.GetString("CheckPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking zone method {0} failed: {1}.
        /// </summary>
        internal static string ParkingZoneFailure {
            get {
                return ResourceManager.GetString("ParkingZoneFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking zone {0} successfully {1}.
        /// </summary>
        internal static string ParkingZoneSuccess {
            get {
                return ResourceManager.GetString("ParkingZoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay method failed: {0}.
        /// </summary>
        internal static string PayParkingFailure {
            get {
                return ResourceManager.GetString("PayParkingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking payed successfully..
        /// </summary>
        internal static string PayParkingSuccess {
            get {
                return ResourceManager.GetString("PayParkingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing ticket failed: {0}.
        /// </summary>
        internal static string RemoveParkingTicketFailure {
            get {
                return ResourceManager.GetString("RemoveParkingTicketFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket successfully removed..
        /// </summary>
        internal static string RemoveParkingTicketSuccess {
            get {
                return ResourceManager.GetString("RemoveParkingTicketSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer between servers failed: {0}.
        /// </summary>
        internal static string ReplicatorFailure {
            get {
                return ResourceManager.GetString("ReplicatorFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully transfered between servers..
        /// </summary>
        internal static string ReplicatorSuccess {
            get {
                return ResourceManager.GetString("ReplicatorSuccess", resourceCulture);
            }
        }
    }
}
